---
title: "Tutorial: Definir Colunas Para Importação"
output:
  html_document:
    df_print: paged
---

```{r,message=F}
library(tidyverse)
library(fs)
```

Obtém nome do arquivo de teste

```{r}
fname <- dir_ls("data",regexp = "MP_EMPENHOS_\\d{6}.TXT")
fname
```

Verifica encoding

```{r}
guess_encoding(fname)
```

Localização Brasil

```{r}
locale_bra <- locale(encoding="ISO-8859-1",
                     decimal_mark = ",",
                     date_format="%d/%m/%Y")
```

Analiza cabeçalho / nome das colunas

```{r}
first_line <- read_lines(fname,n_max=1,locale=locale_bra) %>%
  str_split(fixed(";")) %>%
  first
first_line
```

Numa named-list, especifica quais colunas quer ler e seus tipos:

```{r}
desired_columns <- list(
   Data=col_date()      # Data=col_date(format="%d/%m/%Y"), default em locale_bra
  ,Poder=col_factor()   # Poder="f"
  ,Funcao=col_integer() # Funcao="i"
  ,Valor=col_double()   # Valor="d"
)
```

Verifica indices do cabeçalho

```{r}
which(first_line %in% names(desired_columns))
```

Lê primeiras 10 linhas, só com colunas/tipos especificados em `desired_columns`. Note que `do.call()`, "injeta" `desired_columns` como parâmetros de `cols_only()`.

```{r,message=F,warning=F}
read_delim(
  fname,
  n_max=10,
  delim=fixed(";"),
  trim_ws = T,
  locale=locale_bra,
  col_types = do.call(cols_only,desired_columns)
  # alternative to do.call(): purrr::exec() + splice list (!!!)
  # col_types = exec(cols_only, !!!desired_columns)
)
```


